name: Deploy to DEV

on:
  push:
    branches: 
      - main
      - feature*

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
        
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: '15.x'

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
            
      - name: Yarn Install
        uses: CultureHQ/actions-yarn@v1.0.1
        with:
          args: install
      
      - name: Yarn Build
        uses: CultureHQ/actions-yarn@v1.0.1
        with:
          args: build
 
      - name: Show files
        run: ls -la
        
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: dist-folder
          path: out
  
  deploy:
    name: Deploy to DEV
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: dist-folder
             
      - name: Show files
        run: ls -la
        
      - name: Deploy on DEV
        uses: JamesIves/github-pages-deploy-action@3.7.1
        if: success()
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: . # The folder the action should deploy.
          TARGET_FOLDER: dev 
          CLEAN: true # Automatically remove deleted files from the deploy branch
          #COMMIT_MESSAGE: 'Deploy commit $GITHUB_SHA'
          SILENT: true
